---
- name: Create TPV mutable dir
  ansible.builtin.file:
    state: directory
    path: "{{ tpv_mutable_dir }}"
    mode: 0755
    owner: "{{ galaxy_user.name }}"
    group: "{{ galaxy_user.group }}"

- name: Copy TPV lint and copy script
  ansible.builtin.template:
    src: tpv-lint-and-copy.sh.j2
    dest: "{{ tpv_mutable_dir }}/tpv-lint-and-copy.sh"
    owner: root
    group: root
    mode: 0750
  notify:
    - Execute lint and copy script
